-- Creation Date: 2026-09-26 01:16:59.325004 +0000 UTC 
-- Reason: keep alive 

-- Create table with proper IF NOT EXISTS and schema prefix
CREATE TABLE IF NOT EXISTS public.keep_alive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT DEFAULT ''::text,
    random UUID DEFAULT gen_random_uuid()
);

-- Enable RLS for the table
ALTER TABLE public.keep_alive ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if any to avoid errors
DROP POLICY IF EXISTS "Allow all actions for all roles" ON public.keep_alive;

-- Create policy that allows all roles to perform all actions
CREATE POLICY "Allow all actions for all roles" ON public.keep_alive
FOR ALL
USING (true)
WITH CHECK (true);

-- Grant usage on schema and privileges on the table only to anon role
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.keep_alive TO anon;

INSERT INTO public.keep_alive (name)
VALUES ('placeholder'), ('example');
