package kodama.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF3D6B4F)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFBFE8CA)
internal val md_theme_light_onPrimaryContainer = Color(0xFF002111)
internal val md_theme_light_secondary = Color(0xFF4F6354)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD1E8D5)
internal val md_theme_light_onSecondaryContainer = Color(0xFF0D1F13)
internal val md_theme_light_tertiary = Color(0xFF6B5B3E)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFF5DFB8)
internal val md_theme_light_onTertiaryContainer = Color(0xFF231A05)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFBFDF8)
internal val md_theme_light_onBackground = Color(0xFF191C18)
internal val md_theme_light_surface = Color(0xFFFBFDF8)
internal val md_theme_light_onSurface = Color(0xFF191C18)
internal val md_theme_light_surfaceVariant = Color(0xFFDDE5D9)
internal val md_theme_light_onSurfaceVariant = Color(0xFF414940)
internal val md_theme_light_outline = Color(0xFF71796F)
internal val md_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
internal val md_theme_light_inverseSurface = Color(0xFF2E312D)
internal val md_theme_light_inversePrimary = Color(0xFF95D3AC)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF3D6B4F)
internal val md_theme_light_outlineVariant = Color(0xFFC0C9BF)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF95D3AC)
internal val md_theme_dark_onPrimary = Color(0xFF093920)
internal val md_theme_dark_primaryContainer = Color(0xFF255038)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFBFE8CA)
internal val md_theme_dark_secondary = Color(0xFFB5CCBC)
internal val md_theme_dark_onSecondary = Color(0xFF223528)
internal val md_theme_dark_secondaryContainer = Color(0xFF384B3D)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD1E8D5)
internal val md_theme_dark_tertiary = Color(0xFFD8C39E)
internal val md_theme_dark_onTertiary = Color(0xFF3B2E16)
internal val md_theme_dark_tertiaryContainer = Color(0xFF53442B)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFF5DFB8)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF111411)
internal val md_theme_dark_onBackground = Color(0xFFE1E3DE)
internal val md_theme_dark_surface = Color(0xFF111411)
internal val md_theme_dark_onSurface = Color(0xFFE1E3DE)
internal val md_theme_dark_surfaceVariant = Color(0xFF414940)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9BF)
internal val md_theme_dark_outline = Color(0xFF8B9389)
internal val md_theme_dark_inverseOnSurface = Color(0xFF2E312D)
internal val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
internal val md_theme_dark_inversePrimary = Color(0xFF3D6B4F)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF95D3AC)
internal val md_theme_dark_outlineVariant = Color(0xFF414940)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF3D6B4F)
